### PR TITLE
add ignore_directories setting. Fixes #50

### LINKED ISSUE #50: Would be nice to have ignore_directories setting

### PR DESCRIPTION
**Pull request by maskas**

### CODE REVIEW

**Comment by BrunoDeBarros** [comment]
Looks good to me! Merging. Thanks so much @maskas, it's really good to have help with this! :smile:

**Comment by maskas** [comment]
Not sure how seriuous you are about this project. It would be nice to split it into several classes and have dev version where we have enerything in several files. And then compiled version where we have all the code as it is now or as *.phar. Because now it is a big pain to edit that single large file.

**Comment by BrunoDeBarros** [comment]
Yes, it is a really big pain. Most of the code is just phpseclib, which you're right, should be separate while developing. I agree with what you're saying, that's #37, that would solve that problem.

I haven't gotten around to it because of a lack of time, but I would love to get going with it - maybe it'd make improving things easier for both you and me.

**Comment by BrunoDeBarros** [comment]
@maskas All has been .phar'd. :smile: It should be a lot easier to work on it now. Let me know if you have any ideas/suggestions.

**Comment by maskas** [comment]
Looks so much better now. Great job!

**Comment by BrunoDeBarros** [comment]
I've used PSR-4 for the git-deploy classes and will run Code Sniffer and Coding Standards Fixer as soon as I get a chance, just to clean up the code, make sure it's all OK and decent to work with. And then we'll look into improving this library even further! :smile:

**Pull request merged**
